### PR TITLE
Compopnents, functionalities & styles

### PR DESCRIPTION
**Pull request by jmonto55**
This PR contains all the steps followed to develop the [Todo App](https://github.com/microverseinc/curriculum-react-redux/blob/main/math-magicians/exercises/react_tutorial.md) using React library, including:
- Components layout.
- Hooks implementation to manage state.
- All functionalities to add and remove tasks.
- Styles with sass.

### CODE REVIEW

**Review by flemton — APPROVED** [review]
### Hi @jmonto55   , 



Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✔️ Good and descriptive commit history
✔️No Linter errors
✔️Very professional README
✔️Correct Gitflow
✔️Descriptive PR
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------

**Comment by jmonto55** [comment]
Thank you for the review, @flemton

**Comment by flemton** [comment]
[OPTIONAL] At the FAQ section of your README in the below lines, https://github.com/jmonto55/todo-app-react/blob/938f7965819bcb6e651cb0d5549f0a837043d044/README.md?plain=1#L182-L184
You said data is saved in localstorage but in the video below it seems not, editing or deleting those lines would be very good as to not make it appear as if the page is broken. [Video](https://drive.google.com/file/d/14a8eH3z3amr24efIMclpQ0A0g8Tb6zJD/view?usp=share_link)

**Comment by jmonto55** [comment]
Hi, @flemton, thank you for the review 🦾 I fixed the information in the README file because I did not implement LocalStorage

**Pull request merged**
